#!/usr/bin/env bash

set -euo pipefail

# Split lines greater than 80 characters on blanks

echo Cleaning...
pbpaste | bun /Users/chris/sd/text/wrap.ts > /tmp/clean.txt
pbcopy < /tmp/clean.txt
rm -f /tmp/clean.txt
