#!/usr/bin/env bash

set -euo pipefail

# Split lines greater than 80 characters on blanks

echo Cleaning...
pbpaste | ~/bin/wrap-paragraph-helper.rb > /tmp/clean.txt
pbcopy < /tmp/clean.txt
rm -f /tmp/clean.txt
