#!/usr/bin/env bash

set -euo pipefail

# Find all formattable files from here on down and format them with prettier.

for i in `fd '.*.(ts|tsx|js|css|html)$' | egrep -v '\.(git|jj)' | egrep -v node_modules` ; do
  npx prettier --write "$i"
done
