#!/usr/bin/env bash

set -euo pipefail

# Run the given typescript file as a script. bun may be better...

if [ "x${1-}" = "x" -o "x${2-}" != "x" ] ; then
  echo "Usage: sd ts run file.ts"
  exit 1
fi

# Actual command goes here
node --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));' "${1-}"
