#!/usr/bin/env bash

set -euo pipefail

# Bring up the sqlite3 repl on the current local d1 database, if any

if [ "x${1-}" != "x" ] ; then
  echo "Usage: sd wranger current-db"
  exit 1
fi

if [ $(/bin/ls .wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite  | wc -l) != 1 ] ; then
  echo "Cannot find a single sqlite database in .wrangler."
  exit 1
fi
sqlite3 .wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite
