#!/usr/bin/env bash

set -euo pipefail

# Find files by case-insensitive filename below the current directory. NOTE: Use glob-style patterns, not regex.
if [ "x${1-}" = "x" ] ; then
  echo "Usage: sd rg fn file-glob-pattern"
  exit 1
fi

rg --files --iglob "$1"
