#!/usr/bin/env bash

set -euo pipefail

# Search in files by filename below the current directory. Two args gives a file glob and pattern, one just does a pattern.
if [ "x${1-}" = "x" ] ; then
  echo "Usage: sd rg hacks [file-glob] pattern"
  exit 1
fi

if [ "x${2-}" = "x" ] ; then
  rg $1
else
  rg --iglob $1 $2
fi
