#!/usr/bin/env bash

set -euo pipefail

# Push either the `dev` branch or both `dev` and `main` branches to origin.

if [ "x${1-}" = "x" -o "x${2-}" != "x" ] || [ "x${1-}" != "xdev" -a "x${1-}" != "xmain" -a "x${1-}" != "xboth" ] ; then
  echo "Usage: sd jj push (dev | main | both)"
  exit 1
fi

if [ "x${1-}" = "xdev" -o "x${1-}" = "xboth" ] ; then
  echo "Pushing dev..."
  jj bookmark set dev -r @ ; jj git push --bookmark dev
fi

if [ "x${1-}" = "xmain" -o "x${1-}" = "xboth" ] ; then
  echo "Pushing main..."
  jj bookmark set main -r @ ; jj git push --bookmark main
fi
