#!/usr/bin/env bash

set -euo pipefail

# Check homebrew for updates

brew_update () {
  brew update
  if [ `brew outdated | wc -l` = 0 ] ; then
    echo "Nothing new"
    return
  fi
  
  if [ `brew outdated | egrep -i tmux | wc -l` != 0 ] ; then
    echo "tmux has changed, bailing."
    return
  fi
  
  brew upgrade
  
  if [ -e /opt/homebrew/bin/node  ] ; then
    brew uninstall --ignore-dependencies node
  fi
}

brew_update

echo 'Node:'
source /Users/chris/.nvm/nvm.sh
nvm ls-remote | egrep v18 | tail -3

echo
echo 'Obsidian:'
curl -s https://obsidian.md/ | pup .hero-button-container a button .u-muted text{}
