#!/usr/bin/env bash

set -euo pipefail

# Check homebrew for updates

brew_update () {
  brew update
  if [ `brew outdated | wc -l` = 0 ] ; then
    echo "Nothing new"
    return
  fi
  
  if [ `brew outdated | egrep -i tmux | wc -l` != 0 ] ; then
    echo "tmux has changed, bailing."
    return
  fi
  
  brew upgrade
  
  if [ -e /opt/homebrew/bin/node  ] ; then
    brew uninstall --ignore-dependencies node
    perl -i -ne 'if (/^\#\!/) { print "#!/usr/bin/env node\n"; } else { print }' $(readlink -f /opt/homebrew/bin/wrangler)
  fi
}

brew_update

echo 'Node:'
source /Users/chris/.nvm/nvm.sh
nvm ls-remote | egrep v20 | tail -3

echo
echo 'Obsidian:'
curl -s https://obsidian.md/download | pup 'a[href$=".dmg"]' attr{'href'} | perl -ne '@f = split(/\//); print $f[$#f - 1], "\n";'

echo
echo 'Free tab:'
curl -s https://www.guitar-pro.com/tabs/all | pup 'div#msb-tod > a text{}' | tr -s '\r\n\t' ' ' ; echo
