#!/usr/bin/env bash

set -euo pipefail

# List images in a given PDF

if [ "x${1-}" = "x" -o "x${2-}" != "x" ] ; then
  echo "Usage: sd pdf image-list input_file.pdf"
  exit 1
fi

docker run --rm -v "$PWD:/pdf" gkmr/pdf-tools pdfimages -list /pdf/$1
