#!/usr/bin/env bash

set -euo pipefail

# Extract text from a given PDF to a given file

if [ "x${2-}" = "x" -o "x${3-}" != "x" ] ; then
  echo "Usage: sd pdf text-extract input_file.pdf output_file.txt"
  exit 1
fi

docker run -v $PWD:/pdf gkmr/pdf-tools pdftotext /pdf/$1 /pdf/$2
